/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking.entities;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        User classUnderTest = new User();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
